### ISSUE TITLE
link/href to your linkedin's profile is wrong

### ISSUE THREAD

**Issue by juliomatcom** [dirtyredz/dirtyredz.com#1]
Hello buddy,
The link/href to your linkedin's profile in the footer is broken or wrong, 
nice website! :ok_hand:

**Comment by dirtyredz** [comment]
Thx, for this report. I apologize for taking 3 months to respond.  I apparently had notifications turned off. Been extremely busy on other projects.  I'll get this fixed when time allows for it.
